### ISSUE TITLE
Error: configmap "ecr-updater-config" not found

### ISSUE THREAD

**Issue by Giancarlo1974** [Garbanzo-recipes/backend-nextcloud#1]
Reading your repository istructions
https://github.com/sehucke/ecr-updater

i got this error:
Error: configmap "ecr-updater-config" not found

Can you help me ?

**Comment by dlemper** [comment]
Hi,
I‘m sorry, you opened the issue on the wrong project..
Please open it on the project of @sehucke :)
Closing this ticket now and hope you have a good day!
